title:             Boredom
email:             jh33836782@gmail.com
description:       Otaki Steak & Cheese Pie
author:            ninetyfivejae
baseurl:           "/"
url:               "https://ninetyfivejae.github.io/"

# Social Profiles
twitter_username:
github_username:   ninetyfivejae
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
