title:             Otaki Steak & Cheese Pie
email:             jh33836782@gmail.com
description:       tlswogur
author:            ninetyfivejae
baseurl:           "/"
url:               "https://ninetyfivejae.github.io/"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
